apiVersion: v1
data:
  buildkitd.toml: |
    debug = false
    [worker.containerd]
      namespace = "buildkit"
    [registry."10.121.218.184:30002"]
      http = true
      insecure = true
kind: ConfigMap
metadata:
  name: buildkit
  namespace: default
